[package]
name = "shared_types"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
anyhow = "1.0.66"
crux_core = { path = "../../../crux_core", features = ["typegen"] }
shared = { path = "../shared" }
